/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saul Ponce
 */
public class vista extends javax.swing.JFrame {
    int NORM=2048;
    int SUMA=2033;
    int MULT=2001;
    int SEM;
    double RND;
    int MAX=100;
    double P=0.01;
    double Q=0.99;
    int[] x = new int[100];
    int[] frecuencia;
    public int[] frecuenciaA;
    Double p[] = new Double[100];        
    Double SUM[];
    DefaultTableModel modelo;
    /**
     * Creates new form vistaç
     */
    public vista() {
        initComponents();
        norm.setText(NORM+"");
        suma.setText(SUMA+"");
        mult.setText(MULT+"");
        max.setText(MAX+"");
        valorp.setText(""+P);
        q.setText(""+Q);
        
        frecuencia=new int[100];
        frecuenciaA = new int[100];
        SUM = new Double[100];
        SEM=1500;
        
        modelo =(DefaultTableModel) jTable2.getModel();
        
        valoresX();
        random();
        probabilidades();
        probabilidadesAcumuladas();
        llenarTabla();
        
    }
    
    void llenarTabla(){
        String[] datos= new String[5];
        for (int i = 0; i < x.length; i++) {
            fAcumulada(frecuencia[i],i);
            datos[0]=""+x[i];
            datos[1]=""+frecuencia[i];
            datos[2]=""+frecuenciaA[i];
            datos[3]=""+p[i];
            datos[4]=""+SUM[i];
            
            modelo.addRow(datos);
        }
        
        jTable2.setModel(modelo);
    }
    
    void valoresX(){
        for (int i = 0; i < x.length; i++) {
            x[i]=i+1;
        }
    }
    
    void random(){
        int aux;
        for (int k = 1; k <= MAX; k++) {
                    SEM=(MULT*SEM+SUMA)%NORM;
                    RND=(Double.valueOf(SEM)) / (Double.valueOf(NORM));
                    aux = (int)(100*RND+1);
                    frecuencia(aux);
                }
    }
    
    void frecuencia(int aux){
        for (int i = 0; i < frecuencia.length; i++) {
            if(aux==x[i]){
                frecuencia[i]++;
            }
        }
    }
    
    void fAcumulada(int frecuencia, int i){
        if(i==0){
            frecuenciaA[i]=frecuencia;
        }else if(i==1){
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }else{
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }
    }
    
    void probabilidades(){
        Double aux;
        for (int i = 0; i < x.length; i++) {
            aux = ((double)(P*(Math.pow(Q,(frecuencia[i]-1)))));
            p[i]=redondearDecimales(aux,4);
        }
    }
    
    void probabilidadesAcumuladas(){
        SUM[0]=redondearDecimales(p[0],4);
        for (int j = 1; j < p.length; j++) {
            SUM[j]=redondearDecimales((SUM[j-1]+p[j]),4);;
            }
    }
    
    public static double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        norm = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mult = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        valorp = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        q = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio4/Opera Instantánea_2020-12-19_213552_classroom.google.com.png"))); // NOI18N

        jLabel9.setText("NORM: ");

        jLabel11.setText("SUMA: ");

        jLabel13.setText("MULT: ");

        jLabel15.setText("SEM: ");

        jLabel17.setText("MAX: ");

        jLabel20.setText("P:");

        jLabel19.setText("Q:");

        jTable2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "x", "f(x)", "F(x)", "P(x)", "P(x) Acumulada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(60);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(6, 6, 6)
                                .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(6, 6, 6)
                                .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addGap(6, 6, 6)
                                .addComponent(valorp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addGap(6, 6, 6)
                                .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(valorp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel max;
    private javax.swing.JLabel mult;
    private javax.swing.JLabel norm;
    private javax.swing.JLabel q;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel suma;
    private javax.swing.JLabel valorp;
    // End of variables declaration//GEN-END:variables
}
