/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio7;

import static ejercicio4.vista.redondearDecimales;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saul Ponce
 */
public class vista extends javax.swing.JFrame {
    public int NORM=2048;
    public int SUMA=2033;
    public int MULT=2001;
    public int SEM=500;
    public int I=0;
    public int MAX=1000;
    public int J=0;
    public int N=0;
    public Double[] ProbReal = new Double[1000];
    public Double[] ProbRealA = new Double[1000];
    public int[] frecuencia = new int[1000];
    public int[] frecuenciaA = new int[1000];
    public Double RND;
    public Double x;
    public ArrayList<Double> X;
    DefaultTableModel modelo;
    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        X = new ArrayList();
        norm.setText(""+NORM);
        suma.setText(""+SUMA);
        mult.setText(""+MULT);
        sem.setText(""+SEM);
        max.setText(""+MAX);
        modelo =(DefaultTableModel) jTable2.getModel();
        Random();
        System.out.println("tamaño de X: "+X.size());
        probabilidades();
        probabilidadesAcumuladas();
        llenarTabla();
    }
    
    public void Random(){
        for (J = 1; J <= MAX; J++) {
           SEM=(MULT*SEM+SUMA)%NORM;
           RND=(Double.valueOf(SEM)) / (Double.valueOf(NORM));
           x=redondearDecimales((0.0741)*(-(0.5*Math.pow(RND,2))-RND+5.98),4);
            
           valoresX(x);
           frecuencia(x);
        }
    }
    
    void valoresX(Double x){
        if(!X.contains(x)){
            X.add(x);
        }   
    }

    void frecuencia(Double x){
            if(X.contains(x)){
                frecuencia[X.indexOf(x)]++;
            }
    }
    
    void llenarTabla(){
        String[] datos= new String[5];
        for (int i = 0; i < X.size(); i++) {
            fAcumulada(frecuencia[i],i);
            datos[0]=String.format("%.4f", X.get(i));
            datos[1]=""+frecuencia[i];
            datos[2]=""+frecuenciaA[i];
            datos[3]=""+ProbReal[i];
            datos[4]=""+ProbRealA[i];
            
            modelo.addRow(datos);
        }
        
        jTable2.setModel(modelo);
    }
    
    void fAcumulada(int frecuencia, int i){
        if(i==0){
            frecuenciaA[i]=frecuencia;
        }else if(i==1){
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }else{
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }
    }
    
    void probabilidades(){
        for (int j = 0; j < ProbReal.length; j++) {
            ProbReal[j]=(double)frecuencia[j]/MAX;
        }
    }
    
    void probabilidadesAcumuladas(){
        ProbRealA[0]=redondearDecimales(ProbReal[0],4);
        for (int j = 1; j < ProbReal.length; j++) {
            ProbRealA[j]=redondearDecimales((ProbRealA[j-1]+ProbReal[j]),4);;
            }
    }
    
    public static double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        norm = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mult = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("NORM: ");

        jLabel11.setText("SUMA: ");

        jLabel13.setText("MULT: ");

        jLabel15.setText("SEM: ");

        jLabel17.setText("MAX: ");

        jTable2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "x", "f(x)", "F(x)", "P(x)", "P(x) Acumulada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(60);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(norm, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel max;
    private javax.swing.JLabel mult;
    private javax.swing.JLabel norm;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel suma;
    // End of variables declaration//GEN-END:variables
}
