/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo10;

import static java.lang.Math.pow;

/**
 *
 * @author Saul Ponce
 */
public class vista extends javax.swing.JFrame {

    int NORM=2048;
    int SUMA=2033;
    int MULT=2001;
    int SEM;
    double RND;
    int MAX=100;
    int N=10;
    double P=0.25;
    double Q=0.75;
    int[] frecuencia;
    public int[] frecuenciaA;
    Double p[] = new Double[N];        
    Double SUM[] = new Double[N];
    int I;
    int cont=0;
    int test=0;
    public vista() {
        initComponents();
        norm.setText(NORM+"");
        frecuencia=new int[6];
        frecuenciaA = new int[6];
        p[0]=pow(Q,N);
        probabilidades();
        SUM[0]=p[0];
        probabilidadesAcumuladas();
        SEM=1500;
        I=0;
        random();
        for (int i = 0; i < 6; i++) {
            fAcumulada(frecuencia[i],i);
            jTable2.setValueAt(i, i, 0);
            jTable2.setValueAt(frecuencia[i], i, 1);           
            jTable2.setValueAt(frecuenciaA[i], i, 2);
            jTable2.setValueAt(p[i], i, 3);
            jTable2.setValueAt(SUM[i], i, 4);
        }
    }
    
    void probabilidades(){
        for (int i = 1; i < N; i++) {
            //System.out.println("N: "+N+", i: "+i+", P: "+P+", Q: "+Q+", p[i-1]: "+p[i-1]);
            
            p[i]=(((double)((N-i)+1)/i)*(P/Q)*p[i-1]);
            System.out.println("p["+i+"]: "+p[i]);
            //System.out.println("-------------------------------------------------------------------------");
        }
    }
    
    void probabilidadesAcumuladas(){
        for (int j = 1; j < N; j++) {
            SUM[j]=SUM[j-1]+p[j];
                System.out.println("SUM["+j+"]"+SUM[j]);
            }
    }
    
    void random(){
        int i;
        for (int k = 1; k <= MAX; k++) {
                    SEM=(MULT*SEM+SUMA)%NORM;
                    RND=(Double.valueOf(SEM)) / (Double.valueOf(NORM));
                    i=0;
                    
                    while (RND >= SUM[i]) {
                        i++;
                    }
                    System.out.println("i:"+i);
                     frecuencia(i);
                }
    }
    
    void frecuencia(int RND){
        switch(RND){
            case 0:
                frecuencia[0]++;
                break;
            case 1:
                frecuencia[1]++;
                break;
            case 2:
                frecuencia[2]++;
                break;
            case 3:
                frecuencia[3]++;
                break;
            case 4:
                frecuencia[4]++;
                break;
            case 5:
                frecuencia[5]++;
                break;
        }
    }

    public void fAcumulada(int frecuencia, int i){
        if(i==0){
            frecuenciaA[i]=frecuencia;
        }else if(i==1){
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }else{
            frecuenciaA[i]=(frecuenciaA[i-1]+frecuencia);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        mult = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        norm = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("NORM: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 100, -1, -1));

        jLabel11.setText("SUMA: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 100, -1, -1));

        jLabel13.setText("MULT: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 100, -1, -1));

        jLabel15.setText("SEM: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 100, -1, -1));

        jLabel17.setText("MAX: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 100, -1, -1));
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 50, 14));
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 100, 50, 14));
        getContentPane().add(mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 100, 50, 14));
        getContentPane().add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 50, 14));
        getContentPane().add(norm, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 100, 50, 14));

        jTable2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "x", "f(x)", "F(x)", "P(x)", "P(x) Acumulada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(60);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 639, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel max;
    private javax.swing.JLabel mult;
    private javax.swing.JLabel norm;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel suma;
    // End of variables declaration//GEN-END:variables
}
